version: '3'
services:
  mssql:
    image: mcr.microsoft.com/azure-sql-edge/developer
    container_name: 'opti-mssql'
    user: root
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: pass@word1
    volumes:
      - ./App_Data/data:/var/opt/mssql/data
      - ./App_Data/log:/var/opt/mssql/log
      - ./App_Data/secrets:/var/opt/mssql/secrets
    ports:
      - 1433:1433
